[package]
name = "inline-gdscript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline-gdscript-macros = { path = "inline-gdscript-macros" }
gdnative-core = "0.9.0"
gdnative-sys = "0.9.0"